name: Build and publish Spare Cores images
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
jobs:
  find-jobs:
    runs-on: ubuntu-latest
    name: Find Jobs
    outputs:
      folders: ${{ steps.jobs.outputs.folders }}
    steps:
      - uses: actions/checkout@v6.0.2
      - id: jobs
        uses: kmanimaran/list-folder-action@v4
        with:
          path: ./images

  build-images:
    name: Build image (${{ matrix.folder }} / ${{ matrix.arch }})
    needs: [find-jobs]
    defaults:
      run:
        working-directory: ${{ github.workspace }}/images/${{ matrix.folder }}
    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.find-jobs.outputs.folders )}}
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-latest
          - arch: arm64
            platform: linux/arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
      - name: Log in to the Container registry
        uses: docker/login-action@v4.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.0.0
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6.0.0
        with:
          images: ${{ env.REGISTRY }}/sparecores/${{ matrix.folder }}
          flavor: |
            suffix=-${{ matrix.arch }},onlatest=false
      - name: Build and push Docker image
        uses: docker/build-push-action@v7.1.0
        with:
          context: ${{ github.workspace }}/images/${{ matrix.folder }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/sparecores/${{ matrix.folder }}:buildcache-${{ matrix.arch }}
          cache-to: type=registry,ref=${{ env.REGISTRY }}/sparecores/${{ matrix.folder }}:buildcache-${{ matrix.arch }},mode=max

  merge-manifests:
    name: Merge image manifests (${{ matrix.folder }})
    needs: [find-jobs, build-images]
    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.find-jobs.outputs.folders )}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
      - name: Log in to the Container registry
        uses: docker/login-action@v4.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.0.0
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6.0.0
        with:
          images: ${{ env.REGISTRY }}/sparecores/${{ matrix.folder }}
      - name: Create multi-arch manifests
        run: |
          while IFS= read -r tag; do
            [ -z "$tag" ] && continue
            docker buildx imagetools create \
              --tag "$tag" \
              "$tag-amd64" \
              "$tag-arm64"
          done <<< "${{ steps.meta.outputs.tags }}"